PROJECT_NAME = FoodOrderManagement

BUILD = build

SRC = main.c\
src/food.c\

TEST_SRC = src/food.c\
test/test.c

TEST_OUTPUT = $(BUILD)/Test_$(PROJECT_NAME).out

INC	= -Iinc

PROJECT_OUTPUT = $(BUILD)/$(PROJECT_NAME).out

$(PROJECT_NAME):all

.PHONY: run clean test  doc all

	gcc $(SRC) $(INC) -o $(PROJECT_OUTPUT).out

run:$(PROJECT_NAME)
	./$(PROJECT_OUTPUT).out

test:$(BUILD)
	gcc $(TEST_SRC) $(INC) -o $(TEST_OUTPUT) -lcunit
	./$(TEST_OUTPUT)
	
clean:
	rm -rf $(BUILD)

$(BUILD):
	mkdir build
